# 必填
title: 呓语梦轩

# 以下为选填
author: awaae001(player8635@outlook.com)

#网站图标，可替换
favicon: /avatar.jpg

# 可选
links:
  # github 图标 的链接，换成你自己的，配置时带上 http、https或者//
  github: https://github.com/awaae001
  # 普通链接，可配置多个，以下是示例
  custom:
    - name: Tree
      URL: https://github.com/wujun234/hexo-theme-tree
    - name: UidGenerator
      URL: https://github.com/wujun234/uid-generator-spring-boot-starter


# 可选, giscus 评论系统
# 这里配置 https://giscus.app/zh-CN，将生成好的填在下面
# enable 为 true 时， 填自己的 repo、repo_id、category_id
giscus:
  enable: false
  repo: awaae001/awaae001.github.io
  repo_id: R_kgDOJrn4SA
  category_id: Announcements
  reactions_enabled: 1
  emit_metadata: 0
  input_position: top
  theme: preferred_color_scheme
  lang: zh-CN

# 可选, valine
valine: 
  # 评论
  enableComment: ture
  # 阅读量
  enableCounter: ture
  # valine appID
  appID: gwzbYHtVJuctkE62UMG7AjVI-gzGzoHsz
  # valine appKey
  appKey: gmlZ2lQjkeocUPKluPIikbj0
  placeholder: 在此发表你的网络圣旨，我们不会记录你的IP，你可以畅所欲言。
  avatar: retro

# 是否开启“不蒜子”统计访问量，可选
busuanzi: false

# 底部版权开始年份，不配置默认为今年
siteStartYear: 2023

####### 站外搜索配置 #####
# 站点如果【被搜索引擎收录】，可以配置通过搜索引擎全站搜索
# searchEngine：搜索引擎，不配置则默认为谷歌，可替换为百度等其他搜索引擎的搜索 URL
searchEngine: https://www.baidu.com/s?wd=cdCKr66iB1
#searchEngine: https://www.google.com/search?q=
# homeHost：要搜索的站点域名，不配置默认取当前页面的域名，以下是示例
homeHost:

#设置为 true 之前，要先确保，已经创建了 hexo 的 tags\categories\about 页面
tags: false
categories: false
about: true

# 左侧导航栏，用文件名还是文章名
sidebar:
  # usePostTitle 为 ture 用文章名，不填或为 false 用文件名
  usePostTitle: ture